apiVersion: 1
contactPoints:
  - orgId: 1
    name: Telegram Error Notification
    receivers:
      - uid: dfbbvc9e13zlsb
        type: telegram
        settings:
          bottoken:
          chatid:
          disable_notification: false
          disable_web_page_preview: false
          parse_mode: ''
          message: |
            üö® –û–®–ò–ë–ö–ò –í –ü–†–ò–õ–û–ñ–ï–ù–ò–ò!
          disableResolveMessage: true
